- hosts: backup
  remote_user: aula 
  
  tasks:
    - name: Update packages
      become: yes
      apt:
        update_cache: yes
        state: present

    - name: Install apache
      become: yes
      apt:
        name: apache2
        state: latest

    - name: Copying virtual host file to remote machine
      become: yes
      copy:
        src: ./sys-adm-site.conf
        dest: /etc/apache2/sites-available/sys-adm-site.conf
        owner: root
        group: root
        mode: 0644

    - name: creating  folder for html
      become: yes
      file:
          path: /var/www/sys-adm-site/
          state: directory
          mode: '0755'

    - name: Copying index.html file to remote machine
      become: yes
      copy:
        src: ./index.html
        dest: /var/www/sys-adm-site/index.html
        owner: root
        group: root
        mode: 0644


    - name: Disable default site
      become: yes
      shell: /usr/sbin/a2dissite 000-default.conf
    
    - name: Enable new site
      become: yes
      shell: /usr/sbin/a2ensite sys-adm-site.conf
 
    - name: Restarting apache
      become: yes
      service:
        name: apache2
        state: restarted
